In [1]:
# Do the imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_validate
from sklearn.pipeline import make_pipeline
from sklearn import metrics

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

print('Setup Complete')

Setup Complete


In [2]:
# Load the data
heart_df = pd.read_csv("heart.csv")
heart_df

#1 is heart attack and 0 is no heart attack

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [3]:
#separte the features and the target

X = heart_df.iloc[:,:-1].values
y = heart_df.iloc[:,-1].values
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [4]:
y = heart_df.iloc[:,-1].to_numpy()
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [9]:
#do the train_test split

# --> test or train size ??
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=0)
X_train[:1]

array([[4.30e+01, 0.00e+00, 2.00e+00, 1.22e+02, 2.13e+02, 0.00e+00,
        1.00e+00, 1.65e+02, 0.00e+00, 2.00e-01, 1.00e+00, 0.00e+00,
        2.00e+00]])

In [12]:
#In standardscaler we bring down all the features to a common scale while keeping the same 
#range of the values
scaler = StandardScaler()  

a = scaler.fit(X_train)
X_train = a.transform(X_train)
#The fit method is calculating the mean and variance of each of the features present in our data.
#The transform method is transforming all the features using the respective mean and variance.

X_test = scaler.transform(X_test)

X_train[:1]

array([[ 0.35256528,  0.70243936,  0.9870291 ,  0.02020565, -0.43596979,
        -0.42695628, -0.9825655 ,  1.01189274, -0.72352604,  1.72483977,
         0.96222601,  1.22723311,  1.12135917]])

In [13]:
#initalize and fit with Logistic Regression
model = LogisticRegression(random_state = 42)

#initalize the logistic regressor
clf = model.fit(X_train, y_train)
#Logistic Regression is a Machine Learning classification algorithm that is used to predict the probability
#of a categorical dependent variable

#make predictions
predictions = model.predict(X_test)
print(predictions)

[0 1 1 0 0 0 0 0 0 0 1 1 0 1 1 1 0 1 0 1 1 0 0 0 1 1 0 0 1 1 1 0 1 1 1 1 0
 1 0 0 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 0
 0 1]


In [15]:
#evaluating the performace of our first model
score =clf.score(X_test, y_test)
print(score)

0.8289473684210527


In [17]:
#another way
score2 = metrics.accuracy_score(y_test, predictions)
score2

0.8289473684210527

In [18]:
# --> talk abt cross validation

#cross validate the training set
clf_cv = 0
CV = 5
# YOUR CODE HERE
clf_cv = LogisticRegression(random_state=42).fit(X_train, y_train)
cv = cross_validate(clf_cv, X_train, y_train, cv=CV)

def print_scores(cv):
    #print out cross validation scores
    [print('Crossvalidation fold: {}  Accruacy: {}'.format(n, score)) for n, score in enumerate(cv['test_score'])]
    #print out the mean of the cross validation
    print('Mean train cross validation score {}'.format(cv['test_score'].mean()))
    
print_scores(cv)

Crossvalidation fold: 0  Accruacy: 0.7608695652173914
Crossvalidation fold: 1  Accruacy: 0.8043478260869565
Crossvalidation fold: 2  Accruacy: 0.8666666666666667
Crossvalidation fold: 3  Accruacy: 0.7777777777777778
Crossvalidation fold: 4  Accruacy: 0.8444444444444444
Mean train cross validation score 0.8108212560386473


In [26]:
#--> talk about solver and multiclass

#solver{‘newton-cg’, ‘lbfgs’, ‘liblinear’, ‘sag’, ‘saga’}, default=’lbfgs’
#Algorithm to use in the optimization problem.
#For small datasets, ‘liblinear’ is a good choice, whereas ‘sag’ and ‘saga’ are faster for large ones.
#For multiclass problems, only ‘newton-cg’, ‘sag’, ‘saga’ and ‘lbfgs’ handle multinomial loss;
#  ‘liblinear’ is limited to one-versus-rest schemes.

#multi_class{‘auto’, ‘ovr’, ‘multinomial’}, default=’auto’
#If the option chosen is ‘ovr’, then a binary problem is fit for each label. 
# For ‘multinomial’ the loss minimised is the multinomial loss fit across the entire probability distribution,
#  even when the data is binary.
#  ‘multinomial’ is unavailable when solver=’liblinear’. ‘auto’ selects ‘ovr’ if the data is binary,
#  or if solver=’liblinear’, and otherwise selects ‘multinomial’.

#--> Do we use full dataset X,y or X_train, y_train in cross validation? Confirm it and change the code.
#Also give the reasons why we do so.

# On train 
#Cross-validation is primarily used in applied machine learning to estimate the skill of a machine learning model on unseen data. 
#That is, to use a limited sample in order to estimate how the model is expected to perform in general when used to make predictions on data not used during the training of the model.
#CV is used as a first line estimate of model stability, not to estimate performance in real world settings

#cross validate the training set
clf_cv = LogisticRegression(solver='lbfgs', multi_class='ovr').fit(X_train, y_train)
cv = cross_validate(clf_cv, X, y, cv=5)

def print_scores(cv):
    #print out cross validation scores
    [print('Crossvalidation fold: {}  Accruacy: {}'.format(n, score)) for n, score in enumerate(cv['test_score'])]
    #print out the mean of the cross validation
    print('Mean train cross validation score {}'.format(cv['test_score'].mean()))
    
print_scores(cv)

C:\Users\User\anaconda3\envs\ML\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\envs\ML\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regres

Crossvalidation fold: 0  Accruacy: 0.819672131147541
Crossvalidation fold: 1  Accruacy: 0.8688524590163934
Crossvalidation fold: 2  Accruacy: 0.8360655737704918
Crossvalidation fold: 3  Accruacy: 0.85
Crossvalidation fold: 4  Accruacy: 0.75
Mean train cross validation score 0.8249180327868852


C:\Users\User\anaconda3\envs\ML\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [25]:
#create a pipeline



scaler =StandardScaler();
clf = LogisticRegression(solver='lbfgs', multi_class='multinomial');
pipe = make_pipeline(scaler, clf);
scores = cross_validate(pipe, X, y, cv=5);

print(scores)

{'fit_time': array([0.0130713 , 0.00906992, 0.01214314, 0.01174021, 0.01553655]), 'score_time': array([0.00103998, 0.00636768, 0.        , 0.        , 0.00100756]), 'test_score': array([0.81967213, 0.8852459 , 0.83606557, 0.86666667, 0.76666667])}


In [ ]:
# https://akshita99mehta.medium.com/machine-learning-on-heart-disease-dataset-8a930cefff1d

# follow this link and implement multiple models at once.