## Linear Algebra Quiz #2

![title](./img/2_1.jpeg)

We strongly suggest working with numpy :)

In [6]:
#Do your imports here
import numpy as np

![title](./img/2_2.png)
- Which vectors below define a plane spanned by a linear combination?

In [99]:


def plane(a,b,c):
    #returns false if the vectors do define a plane and returns which are those vectors if true
    
    matrix = np.stack((a,b,c)) #Join a sequence of arrays along a new axis.
    
    lambdas, V = np.linalg.eig(matrix.T) 
    
    e = 0.000000001
    
    plane_test = abs(lambdas) > e 
    
    if plane_test.sum() >= 2:
        
        print('Vectors form a plane!')
        
        vectors = matrix[plane_test]
        return vectors
    else:
        print('Vectors are all linearly dependent. No plane exists.')
        
# Harder exercise

#def complete_plane(#inputs):
    
#returns the first set of vectors to complete a plane, false otherwise

In [103]:
def plane_modula(a,b,c):
    #returns false if the vectors do define a plane and returns which are those vectors if true
    ab = a%b
    bc = b%c
    ac = a%c
    zero_vec = np.zeros(len(a), dtype = int)
    
    if ab != zero_vec:
        return f'Vectors form a plane!  a: {a}   b: {b}'
    elif bc != zero_vec:
        return f'Vectors form a plane! b: {b} , c: {c}'
    elif ac != zero_vec:
        return f'Vectors form a plane! c: {a} c: {c}'
    else:
        print('Vectors are all linearly dependent. No plane exists.')

In [107]:
ab = a%b
bc = b%c
ac = a%c
zero_vec = np.zeros(len(a), dtype = int)

In [112]:
print(a%b)
print(ab)
print(zero_vec)
if ab == zero_vec :
    print(True)

[1 0 1]
[1 0 1]
[0 0 0]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [84]:
a = np.array([1,2,3])
b = np.array([2,2,2])
c = np.array([8,8,8])

In [104]:
print(plane_modula(a,b,c))
print(plane(a,b,c))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
#any linear combiniation for a plane
#which dont forms a plane 
#linear dependet for the second equation /5 then its the same

![title](./img/2_3.png)
- What is the solution for a and b?

In [ ]:
# do you need a function for this? What is the most efficient way to solve it?


![title](./img/2_4.png)
- What is the solution for a and b?

In [ ]:
# Idem. Do you need a function for this? What is the most efficient way to solve it?

#same equation but diffrent solution !!! Wrong !!!!!!!